### ISSUE TITLE
not showing trainer info

### ISSUE THREAD

**Issue by kuro2052** [Nader-Sl/Hackemon#74]
The bot seems to work fine. but there is no info showing in the left upper conner
![hm](https://cloud.githubusercontent.com/assets/20905206/17733107/a5c5830a-6492-11e6-98ec-39279112bb3e.png)

**Comment by cirios** [comment]
any solution? I have the same problem

**Comment by mrsniffin** [comment]
same here.

**Comment by PokemonAddict** [comment]
same here :(

**Comment by PokemonAddict** [comment]
but the recycling and co is still working

**Comment by aboxx** [comment]
delete the settings.json file in the main folder. this will obviously delete your saved settings, but should fix the problem.

**Comment by CrystalEcho** [comment]
Did it worked for you @aboxx? I tried doing that but still no trainer infos.

**Comment by aboxx** [comment]
@CrystalEcho Yes it happened several times and has worked. Make sure you close the program and delete then reopen it. You can also try to re-download Hackemon.

**Comment by CrystalEcho** [comment]
I tried deleting settings.json and rerun the app but still no trainer info, I tried deleting the whole folder and re-download the files but still not working. 😬😬😬

**Comment by mits1988** [comment]
im having the same issue but I wanted to ask-

Even though the trainer info is not showing is my account still catching pokemon and gaining xp?

**Comment by cirios** [comment]
yes however

**Comment by mits1988** [comment]
thank you @cirios

**Comment by Muuuri** [comment]
The pokemon section aint working for me aswell as the trainer info.

**Comment by thorclaw** [comment]
Naders updated the bot yesterday, i think he may have forgot to do something.

**Comment by mits1988** [comment]
has anyone else tried to delete the file, delete and re-install it? and has it worked?

**Comment by cirios** [comment]
yes but nothing

**Comment by frodo024** [comment]
Worked fine for me up until update yesterday as well

**Comment by kipperjx2** [comment]
same issue here

**Comment by kipperjx2** [comment]
however we can confirm that it is infact still collecting resources?

**Comment by kipperjx2** [comment]
Login to phone choose team, etc fixed

**Comment by CrystalEcho** [comment]
Still not working @kipperjx2

**Comment by cirios** [comment]
**still nothing**

**Comment by daisukeDan** [comment]
same. me too.
and Pokemon list didn't show
